### ISSUE TITLE
Consistent Basic Element Style Selectors

### ISSUE THREAD

**Issue by rsandor** [fastly/epoch#29]
Currently, overriding styles like fill and stroke colors require different CSS selectors depending on the type of chart. For instance, to change the styles of **lines**, **areas**, **dots**, and heat map **buckets** one uses the following selector pattern:

``` css
.layer-1 .line { stroke: blue; }
.layer-1 .area { fill: cyan; }
.layer-1 .dot { fill: orange; }
.layer-1 .bucket { fill: green; }
```

And to change bars and pie slices one uses _two entirely different_ selector patterns:

``` css
.bar.layer-1 { fill: gray; }
.arc.layer-1 path { fill: black; }
```

While the current approach makes implementing the charts a little easier, it would be much better for application programmers if we had a consistent selector pattern. I am partial to this:

``` css
.layer-1 .line { stroke: blue }
```
